for field in SOURCE_TYPE SOURCE DETAIL_TYPE_ID BASE_TYPE SUB_TYPE DETAIL_TYPE EXT_TYPE TIME DD TT S_IP_T S_IP_N D_IP_T D_IP_N S_PORT D_PORT C_FLAG MON_POINT_LOCATION_TYPE MON_POINT_LOCATION_REGION MON_POINT_LOCATION_ISP MON_POINT_LOCATION_PLACE MON_POINT_LOCATION_NET MON_POINT_LOCATION_GATE RETURN_VALUE
do
	echo "<parametermap columnindex=\"8\" columnname=\"$field\" columntype=\"String\"/>"
done
